// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Database;

#nullable disable

namespace Portfolio.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260824160305_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ContentSeedRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("SeededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seeded_at");

                    b.HasKey("Id")
                        .HasName("pk_content_seeds");

                    b.ToTable("content_seeds", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.EducationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_education");

                    b.ToTable("education", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.EducationTranslationRow", b =>
                {
                    b.Property<string>("EducationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("education_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degree");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.HasKey("EducationId", "LanguageCode")
                        .HasName("pk_education_translations");

                    b.ToTable("education_translations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceHighlightRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_experience_highlights");

                    b.HasIndex("ExperienceId", "LanguageCode", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_experience_highlights_experience_id_language_code_ordinal");

                    b.ToTable("experience_highlights", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceParallelRow", b =>
                {
                    b.Property<string>("ExperienceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<string>("ParallelExperienceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parallel_experience_id");

                    b.HasKey("ExperienceId", "ParallelExperienceId")
                        .HasName("pk_experience_parallel_roles");

                    b.ToTable("experience_parallel_roles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<int>("EndMonth")
                        .HasColumnType("integer")
                        .HasColumnName("end_month");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("start_month");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_experiences");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_experiences_ordinal");

                    b.ToTable("experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_experiences_end_month", "end_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_experiences_period", "(end_year * 12 + end_month) >= (start_year * 12 + start_month)");

                            t.HasCheckConstraint("ck_experiences_start_month", "start_month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTeamRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team");

                    b.HasKey("Id")
                        .HasName("pk_experience_teams");

                    b.HasIndex("ExperienceId", "LanguageCode", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_experience_teams_experience_id_language_code_ordinal");

                    b.ToTable("experience_teams", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTechnologyRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technology");

                    b.HasKey("Id")
                        .HasName("pk_experience_technologies");

                    b.HasIndex("ExperienceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_experience_technologies_experience_id_ordinal");

                    b.ToTable("experience_technologies", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTranslationRow", b =>
                {
                    b.Property<string>("ExperienceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.HasKey("ExperienceId", "LanguageCode")
                        .HasName("pk_experience_translations");

                    b.ToTable("experience_translations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProfileRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("availability");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProfileTranslationRow", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("headline");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("SummaryTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_template");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("ProfileId", "LanguageCode")
                        .HasName("pk_profile_translations");

                    b.ToTable("profile_translations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("experience_id");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ExperienceId")
                        .HasDatabaseName("ix_projects_experience_id");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_projects_ordinal");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectSourceRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CheckedOn")
                        .HasColumnType("date")
                        .HasColumnName("checked_on");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_project_sources");

                    b.HasIndex("ProjectId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_project_sources_project_id_ordinal");

                    b.ToTable("project_sources", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectTechnologyRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technology");

                    b.HasKey("Id")
                        .HasName("pk_project_technologies");

                    b.HasIndex("ProjectId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_project_technologies_project_id_ordinal");

                    b.ToTable("project_technologies", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectTranslationRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<string>("Contribution")
                        .HasColumnType("text")
                        .HasColumnName("contribution");

                    b.Property<string>("CvSummary")
                        .HasColumnType("text")
                        .HasColumnName("cv_summary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("ProjectId", "LanguageCode")
                        .HasName("pk_project_translations");

                    b.ToTable("project_translations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillCategoryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id")
                        .HasName("pk_skill_categories");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_skill_categories_ordinal");

                    b.ToTable("skill_categories", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillCategoryTranslationRow", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("CategoryId", "LanguageCode")
                        .HasName("pk_skill_category_translations");

                    b.ToTable("skill_category_translations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillItemRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_id");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id")
                        .HasName("pk_skill_items");

                    b.HasIndex("CategoryId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_items_category_id_ordinal");

                    b.ToTable("skill_items", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SocialLinkRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_social_links");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_social_links_ordinal");

                    b.ToTable("social_links", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SpokenLanguageRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_spoken_languages");

                    b.HasIndex("ProfileId", "LanguageCode", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_spoken_languages_profile_id_language_code_ordinal");

                    b.ToTable("spoken_languages", (string)null);
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.EducationTranslationRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.EducationRow", null)
                        .WithMany("Translations")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_education_translations_education_education_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceHighlightRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany("Highlights")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experience_highlights_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceParallelRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany("ParallelRoles")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experience_parallel_roles_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTeamRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany("Teams")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experience_teams_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTechnologyRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany("Technologies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experience_technologies_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceTranslationRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany("Translations")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experience_translations_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProfileTranslationRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ProfileRow", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_translations_profiles_profile_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ExperienceRow", null)
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_experiences_experience_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectSourceRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ProjectRow", null)
                        .WithMany("Sources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_sources_projects_project_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectTechnologyRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ProjectRow", null)
                        .WithMany("Technologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_technologies_projects_project_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectTranslationRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ProjectRow", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_translations_projects_project_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillCategoryTranslationRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.SkillCategoryRow", null)
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_category_translations_skill_categories_category_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillItemRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.SkillCategoryRow", null)
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_items_skill_categories_category_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SpokenLanguageRow", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Database.ProfileRow", null)
                        .WithMany("SpokenLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spoken_languages_profiles_profile_id");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.EducationRow", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ExperienceRow", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("ParallelRoles");

                    b.Navigation("Teams");

                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProfileRow", b =>
                {
                    b.Navigation("SpokenLanguages");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.ProjectRow", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Database.SkillCategoryRow", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
